### ISSUE TITLE
Create CSA Document styling according to existing document

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/csand-style#1]
@pierrefortier we will be using this style for CSA Documents:

https://downloads.cloudsecurityalliance.org/assets/research/security-guidance/security-guidance-v4-FINAL.pdf

Could you help us craft something like this for HTML, and that works with paginated output?

Thanks!

**Comment by pierrefortier** [comment]
Sounds good!

**Comment by pierrefortier** [comment]
Made an initial update to match the style of the provided CSA doc. 

I've started making the layout compatible with paginated output – but it's still a work in progress.

**Comment by ronaldtse** [comment]
@pierrefortier nicely done, we'll want the section title styles and font styling to match etc. Understand it's a WIP. Thanks!

**Comment by ronaldtse** [comment]
@pierrefortier could we also have a more different style from CSD -- e.g., the orange/green bars can be replaced with CSA colors, and maybe adjust layout and stuff to make it look more different. They're two separate organizations so probably prefer more individuality rather than cookie cutter styling 😉

**Comment by pierrefortier** [comment]
Thanks Ron, sounds good! :)

**Comment by ronaldtse** [comment]
How's it going @pierrefortier ? I have a document that needs to proceed with some styling 😉

**Comment by pierrefortier** [comment]
Hi Ron, sorry about the delays. It's a little crazy here!

I made a small update to the styling and print output. I've tried to match the headers and text as much as possible to the pdf. I feel like the main element that makes it seem "samey" to the other documents is the sidebar. Any suggestions for that one to help distinguish it?

**Comment by ronaldtse** [comment]
@pierrefortier how about we change the text colors (to the CSA brand colors) or add some graphic icons?

You know what? It's looking really nice already. 😉

**Comment by ronaldtse** [comment]
@pierrefortier would you have time for this shortly? Just a few color changes. Thanks 😉

**Comment by pierrefortier** [comment]
Hi Ron, just made a quick update. Changed the header colors to go along with brand colors and hierarchy.

**Comment by ronaldtse** [comment]
@pierrefortier thanks -- can we at last update the doc-status and doc-type colors for the brand? Then we're all done. Appreciate it! (screenshot below)

![screen shot 2018-06-07 at 6 56 30 am](https://user-images.githubusercontent.com/11865/41069332-070c406a-6a20-11e8-9a64-943afe3c566d.png)

**Comment by pierrefortier** [comment]
Updated! :)

**Comment by ronaldtse** [comment]
Thank you @pierrefortier ! It's all good now (the HTML part)!
